//! Declarative networking policy: traits and app extensions that let each
//! subsystem register its own replicated components and network events.
//!
//! Components and events opt into networking by deriving [`Replicated`],
//! [`ClientEvent`], or [`ServerEvent`] from `super-battle-royale-macros`. Each
//! gameplay plugin then calls [`NetworkAppExt::register_networked`] for the types
//! it owns. The registrations are collected in [`NetworkRegistry`] and applied
//! later by the client/server networking plugins, *after* `RepliconPlugins` has
//! initialized the replication registry. This lets unit tests build individual
//! gameplay plugins without needing the full networking stack.

use bevy::prelude::*;
use serde::Serialize;
use serde::de::DeserializeOwned;

/// A deferred registration callback. Stored in [`NetworkRegistry`] by gameplay
/// plugins and flushed by the client/server net plugins once `RepliconPlugins`
/// is ready.
type RegisterFn = Box<dyn FnOnce(&mut App) + Send + Sync + 'static>;

/// Collection of deferred network registrations. Gameplay plugins push callbacks
/// here; the transport plugins flush them after `RepliconPlugins` is added.
#[derive(Resource, Default)]
pub struct NetworkRegistry {
    pending: Vec<RegisterFn>,
}

impl NetworkRegistry {
    /// Push a registration callback. Called by [`NetworkAppExt::register_networked`].
    pub fn push(&mut self, f: RegisterFn) {
        self.pending.push(f);
    }

    /// Apply every pending registration and clear the list. Must be called after
    /// `RepliconPlugins` is added to the app.
    pub fn apply(&mut self, app: &mut App) {
        let pending = std::mem::take(&mut self.pending);
        for f in pending {
            f(app);
        }
    }
}

/// Implemented by derive macro for every replicated component and network event.
/// The [`register_networked`](NetworkAppExt::register_networked) app extension
/// uses this to add the type to `bevy_replicon`.
pub trait NetworkRegistered {
    fn register(app: &mut App);
}

/// Marker trait for components that replicate from the authoritative side to
/// connected clients. Generated by `#[derive(Replicated)]`.
pub trait ReplicatedComponent:
    Component + Serialize + DeserializeOwned + Clone + Send + Sync + 'static
{
}

/// Marker trait for events that travel over the network (client→server or
/// server→client). Generated by `#[derive(ClientEvent)]` and
/// `#[derive(ServerEvent)]`.
pub trait NetworkEvent: Event + Serialize + DeserializeOwned + Send + Sync + 'static {}

/// App extension for registering gameplay types that participate in networking.
pub trait NetworkAppExt {
    /// Register a replicated component or network event.
    ///
    /// Use this in each subsystem's plugin for the types it defines:
    ///
    /// ```ignore
    /// impl Plugin for PlayerPlugin {
    ///     fn build(&self, app: &mut App) {
    ///         app.register_networked::<Player>()
    ///            .register_networked::<PlayerColor>()
    ///            .register_networked::<PlayerInput>();
    ///     }
    /// }
    /// ```
    ///
    /// The registration is deferred until the client/server net plugin flushes
    /// [`NetworkRegistry`], so this is safe to call even when `RepliconPlugins`
    /// has not been added yet.
    fn register_networked<T: NetworkRegistered>(&mut self) -> &mut Self;

    /// Register many networked types at once.
    fn register_networked_many<T: NetworkRegisteredGroup>(&mut self) -> &mut Self;
}

impl NetworkAppExt for App {
    fn register_networked<T: NetworkRegistered>(&mut self) -> &mut Self {
        self.init_resource::<NetworkRegistry>();
        self.world_mut()
            .resource_mut::<NetworkRegistry>()
            .push(Box::new(|app| T::register(app)));
        self
    }

    fn register_networked_many<T: NetworkRegisteredGroup>(&mut self) -> &mut Self {
        self.init_resource::<NetworkRegistry>();
        self.world_mut()
            .resource_mut::<NetworkRegistry>()
            .push(Box::new(|app| T::register_all(app)));
        self
    }
}

/// Sealed helper trait for [`NetworkAppExt::register_networked_many`]. Implemented
/// by tuples of [`NetworkRegistered`] types.
pub trait NetworkRegisteredGroup {
    fn register_all(app: &mut App);
}

macro_rules! impl_group {
    ($($T:ident),+) => {
        impl<$($T: NetworkRegistered),+> NetworkRegisteredGroup for ($($T,)+) {
            fn register_all(app: &mut App) {
                $(<$T as NetworkRegistered>::register(app);)+
            }
        }
    };
}

impl_group!(A);
impl_group!(A, B);
impl_group!(A, B, C);
impl_group!(A, B, C, D);
impl_group!(A, B, C, D, E);
impl_group!(A, B, C, D, E, F);
impl_group!(A, B, C, D, E, F, G);
impl_group!(A, B, C, D, E, F, G, H);

/// Initialize the deferred network registry. Call once from any plugin that is
/// guaranteed to be added before gameplay plugins (e.g. [`GamePlugin`](crate::game::GamePlugin)).
pub fn init_network_registry(app: &mut App) {
    app.init_resource::<NetworkRegistry>();
}

/// Apply all deferred network registrations. The client and server net plugins
/// call this after adding `RepliconPlugins`.
pub fn apply_network_registry(app: &mut App) {
    let pending: Vec<RegisterFn> = app
        .world_mut()
        .get_resource_mut::<NetworkRegistry>()
        .map(|mut r| std::mem::take(&mut r.pending))
        .unwrap_or_default();
    for f in pending {
        f(app);
    }
}

/// Convenience re-export of the derive macros so gameplay modules only need to
/// import from `crate::game::net`.
pub use super_battle_royale_macros::{ClientEvent, Replicated, ServerEvent};

#[cfg(test)]
mod tests {
    use bevy::prelude::*;
    use bevy::state::app::StatesPlugin;
    use serde::{Deserialize, Serialize};

    use super::{NetworkAppExt, NetworkRegistry, Replicated, apply_network_registry};

    /// Dummy replicated component for registry tests.
    #[derive(Component, Serialize, Deserialize, Clone, Copy, Debug, Replicated)]
    struct DummyComponent;

    #[test]
    fn apply_network_registry_clears_pending_registrations() {
        let mut app = App::new();
        app.add_plugins((
            MinimalPlugins,
            StatesPlugin,
            bevy_replicon::prelude::RepliconPlugins,
        ));
        app.register_networked::<DummyComponent>();

        apply_network_registry(&mut app);

        let registry = app.world().resource::<NetworkRegistry>();
        assert!(
            registry.pending.is_empty(),
            "apply_network_registry must drain all pending registrations"
        );
    }
}
